# For full config options, check the docs:
#    docs.serverless.com

service: wecarry-lambdas

provider:
  name: aws
  runtime: go1.x
  timeout: 240
  versionFunctions: false
  memorySize: 64

  # you can overwrite defaults here
  #  stage: dev
  region: us-east-1

  # you can define service wide environment variables here
  environment:
    stage: ${self:custom.stage}
    region: ${self:custom.region}

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}

package:
  exclude:
    - ./**
  include:
    - ../../bin/**

functions:
  cron:
    handler: bin/maintenance
    events:
      - schedule: cron(* * * * ? *)
